### ISSUE TITLE
"Error" in installing but "installed and available" in checking

### ISSUE THREAD

**Issue by renkun-ken** [jbryer/Rgitbook#8]
This is a great package! But some weird errors always occur. I want to know what happens. I tried both R terminal and RStudio with Admin account.

```
> library(Rgitbook)
Warning message:
replacing previous import by ‘utils::cite’ when loading ‘Rgitbook’
```

```
> installGitbook()
npm http GET https://registry.npmjs.org/gitbook
npm http 304 https://registry.npmjs.org/gitbook
npm http GET https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/marked/0.3.2
npm http GET https://registry.npmjs.org/marked-text-renderer/0.0.1
npm http GET https://registry.npmjs.org/swig/1.3.2
npm http GET https://registry.npmjs.org/lunr/0.5.2
npm http GET https://registry.npmjs.org/commander/2.2.0
npm http GET https://registry.npmjs.org/fstream-ignore/0.0.7
npm http GET https://registry.npmjs.org/send/0.2.0
npm http GET https://registry.npmjs.org/tmp/0.0.23
npm http GET https://registry.npmjs.org/semver/2.2.1
npm http GET https://registry.npmjs.org/fs-extra/0.8.1
npm http GET https://registry.npmjs.org/highlight.js/8.0.0
npm http GET https://registry.npmjs.org/gitbook-plugin/0.0.2
npm http GET https://registry.npmjs.org/gitbook-plugin-mixpanel/0.0.2
npm http GET https://registry.npmjs.org/gitbook-plugin-mathjax/0.0.3
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/marked-text-renderer/0.0.1
npm http 304 https://registry.npmjs.org/marked/0.3.2
npm http 304 https://registry.npmjs.org/q/1.0.1
npm http 304 https://registry.npmjs.org/swig/1.3.2
npm http 304 https://registry.npmjs.org/lunr/0.5.2
npm http 304 https://registry.npmjs.org/fstream-ignore/0.0.7
npm http 304 https://registry.npmjs.org/tmp/0.0.23
npm http 304 https://registry.npmjs.org/commander/2.2.0
npm http 304 https://registry.npmjs.org/send/0.2.0
npm http 304 https://registry.npmjs.org/semver/2.2.1
npm http 304 https://registry.npmjs.org/fs-extra/0.8.1
npm http 304 https://registry.npmjs.org/gitbook-plugin-mixpanel/0.0.2
npm http 304 https://registry.npmjs.org/gitbook-plugin/0.0.2
npm http 304 https://registry.npmjs.org/highlight.js/8.0.0
npm http 304 https://registry.npmjs.org/gitbook-plugin-mathjax/0.0.3
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/fresh
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/jsonfile
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/ncp
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/jsonfile
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/fresh
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/lru-cache
C:\Users\Kun\AppData\Roaming\npm\gitbook -> C:\Users\Kun\AppData\Roaming\npm\node_modules\gitbook\bin\gitbook.js
gitbook@0.3.1 C:\Users\Kun\AppData\Roaming\npm\node_modules\gitbook
â”œâ”€â”€ commander@2.2.0
â”œâ”€â”€ gitbook-plugin-mathjax@0.0.3
â”œâ”€â”€ gitbook-plugin-mixpanel@0.0.2
â”œâ”€â”€ gitbook-plugin@0.0.2
â”œâ”€â”€ marked-text-renderer@0.0.1
â”œâ”€â”€ tmp@0.0.23
â”œâ”€â”€ marked@0.3.2
â”œâ”€â”€ q@1.0.1
â”œâ”€â”€ semver@2.2.1
â”œâ”€â”€ lodash@2.4.1
â”œâ”€â”€ highlight.js@8.0.0
â”œâ”€â”€ lunr@0.5.2
â”œâ”€â”€ fs-extra@0.8.1 (jsonfile@1.1.1, rimraf@2.2.6, ncp@0.4.2, mkdirp@0.3.5)
â”œâ”€â”€ send@0.2.0 (debug@0.8.1, fresh@0.2.2, range-parser@1.0.0, mime@1.2.11)
â”œâ”€â”€ swig@1.3.2 (optimist@0.6.1, uglify-js@2.4.13)
â””â”€â”€ fstream-ignore@0.0.7 (inherits@2.0.1, fstream@0.1.25, minimatch@0.2.14)
npm http GET https://registry.npmjs.org/gitbook-pdf
npm http 304 https://registry.npmjs.org/gitbook-pdf
npm http GET https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/commander/2.2.0
npm http GET https://registry.npmjs.org/phantomjs/1.9.7-3
npm http 304 https://registry.npmjs.org/q/1.0.1
npm http 304 https://registry.npmjs.org/commander/2.2.0
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/phantomjs/1.9.7-3
npm http GET https://registry.npmjs.org/adm-zip/0.2.1
npm http GET https://registry.npmjs.org/ncp/0.4.2
npm http GET https://registry.npmjs.org/kew
npm http GET https://registry.npmjs.org/npmconf/0.0.24
npm http GET https://registry.npmjs.org/mkdirp/0.3.5
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/npmconf/0.0.24
npm http 304 https://registry.npmjs.org/adm-zip/0.2.1
npm http 304 https://registry.npmjs.org/mkdirp/0.3.5
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/kew
npm http 304 https://registry.npmjs.org/ncp/0.4.2
npm http GET https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/osenv/0.0.3
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/config-chain
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/osenv/0.0.3
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/proto-list
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/proto-list

> phantomjs@1.9.7-3 install C:\Users\Kun\AppData\Roaming\npm\node_modules\gitbook-pdf\node_modules\phantomjs
> node install.js

Downloading http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-windows.zip
Saving to C:\Users\Kun\AppData\Local\Temp\phantomjs\phantomjs-1.9.7-windows.zip

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
npm ERR! phantomjs@1.9.7-3 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-3 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\PROGRA~1\\nodejs\\\\node.exe" "C:\\PROGRA~1\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gitbook-pdf" "-g"
npm ERR! cwd C:\Users\Kun\Documents\R
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm
Error in installGitbook() : 
  gitbook installation failed. Typically installing as root/Administrator from the terminal/console works:
   npm install gitbook -g
   npm install gitbook-pdf -g
   npm install gitbook-plugin
In addition: Warning message:
running command 'npm install gitbook-pdf -g' had status 1 
```

Some errors in installation, but `checkForGitbook` reports it's avaiable.

```
> checkForGitbook()

Usage: npm <command>

where <command> is one of:
    add-user, adduser, apihelp, author, bin, bugs, c, cache,
    completion, config, ddp, dedupe, deprecate, docs, edit,
    explore, faq, find, find-dupes, get, help, help-search,
    home, i, info, init, install, isntall, issues, la, link,
    list, ll, ln, login, ls, outdated, owner, pack, prefix,
    prune, publish, r, rb, rebuild, remove, repo, restart, rm,
    root, run-script, s, se, search, set, show, shrinkwrap,
    star, stars, start, stop, submodule, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Kun\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@1.4.3 C:\PROGRA~1\nodejs\node_modules\npm

  Usage: gitbook [options] [command]

  Commands:

    build [options] [source_dir] Build a gitbook from a directory
    serve [options] [source_dir] Build then serve a gitbook from a directory
    pdf [options] [source_dir] Build a gitbook as a PDF
    ebook [options] [source_dir] Build a gitbook as a eBook
    init [source_dir]      Create files and folders based on contents of SUMMARY.md

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

gitbook is installed and available
```

Creating a new gitbook works fine, but building it always ends up with errors.

```
> newGitbook("testbook")

Usage: npm <command>

where <command> is one of:
    add-user, adduser, apihelp, author, bin, bugs, c, cache,
    completion, config, ddp, dedupe, deprecate, docs, edit,
    explore, faq, find, find-dupes, get, help, help-search,
    home, i, info, init, install, isntall, issues, la, link,
    list, ll, ln, login, ls, outdated, owner, pack, prefix,
    prune, publish, r, rb, rebuild, remove, repo, restart, rm,
    root, run-script, s, se, search, set, show, shrinkwrap,
    star, stars, start, stop, submodule, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Kun\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@1.4.3 C:\PROGRA~1\nodejs\node_modules\npm

  Usage: gitbook [options] [command]

  Commands:

    build [options] [source_dir] Build a gitbook from a directory
    serve [options] [source_dir] Build then serve a gitbook from a directory
    pdf [options] [source_dir] Build a gitbook as a PDF
    ebook [options] [source_dir] Build a gitbook as a eBook
    init [source_dir]      Create files and folders based on contents of SUMMARY.md

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

Creating testbook
Writing .bookignore...
Writing .gitignore...
Writing README.md...
Writing SUMMARY.md...
Writing references.rmd...
Writing references.bib...
Writing 1 Bibtex entries ... OK
Results written to file 'references.bib'
Writing 1 Bibtex entries ... OK
Results written to file 'references.bib'
Writing 1 Bibtex entries ... OK
Results written to file 'references.bib'
Writing 1 Bibtex entries ... OK
Results written to file 'references.bib'
You can now open README.md and SUMMARY.md. Once you are done 
editting SUMMARY.md, initGitbook() will create the file and folder 
structure for your new Gitbook.
Current working directory: C:/Users/Kun/Documents/R/testbook
```

```
> buildGitbook()
Building R markdown files...


processing file: references.Rmd
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: setup (with options) 
List of 4
 $ echo   : logi FALSE
 $ results: chr "hide"
 $ message: logi FALSE
 $ warning: logi FALSE

  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: bibliography (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.................................................................| 100%
  ordinary text without R code


output file: references.md

R Markdown files successfully built!

Usage: npm <command>

where <command> is one of:
    add-user, adduser, apihelp, author, bin, bugs, c, cache,
    completion, config, ddp, dedupe, deprecate, docs, edit,
    explore, faq, find, find-dupes, get, help, help-search,
    home, i, info, init, install, isntall, issues, la, link,
    list, ll, ln, login, ls, outdated, owner, pack, prefix,
    prune, publish, r, rb, rebuild, remove, repo, restart, rm,
    root, run-script, s, se, search, set, show, shrinkwrap,
    star, stars, start, stop, submodule, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Kun\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@1.4.3 C:\PROGRA~1\nodejs\node_modules\npm

  Usage: gitbook [options] [command]

  Commands:

    build [options] [source_dir] Build a gitbook from a directory
    serve [options] [source_dir] Build then serve a gitbook from a directory
    pdf [options] [source_dir] Build a gitbook as a PDF
    ebook [options] [source_dir] Build a gitbook as a eBook
    init [source_dir]      Create files and folders based on contents of SUMMARY.md

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

Starting build ...
[ { [Error: EEXIST, mkdir 'C:\Users\Kun\Documents\R\testbook\_book\gitbook\plugins\gitbook-plugin-mathjax']
    errno: 47,
    code: 'EEXIST',
    path: 'C:\\Users\\Kun\\Documents\\R\\testbook\\_book\\gitbook\\plugins\\gitbook-plugin-mathjax' } ]
```

Only a index page is built, others like the next page (section 1/README) is not.

Here's my session info:

```
> sessionInfo()
R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rgitbook_0.9

loaded via a namespace (and not attached):
 [1] bibtex_0.3-6        evaluate_0.5.3      formatR_0.10        httr_0.3           
 [5] knitcitations_0.5-0 knitr_1.5           RCurl_1.95-4.1      stringr_0.6.2      
 [9] tools_3.1.0         XML_3.98-1.1        xtable_1.7-3       
```

**Comment by jbryer** [comment]
Can you try both updating RGitbook and gitbook? Seems are changing so fast I am not sure if this has been fixed. You will likely have to install gitbook from the Terminal using the following command:
sudo npm install gitbook -g

I may have to delete the installGitbook since I cannot find a way for it to work reliably on all systems.

**Comment by renkun-ken** [comment]
I cloned GitbookIO/gitbook and installed it and build it myself, it works correctly with Rgitbook now.
